---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke2
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke2
  template:
    metadata:
      labels:
        app: gke2
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - GKE v2
