---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke1
  template:
    metadata:
      labels:
        app: gke1
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - GKE v1
