---
apiVersion: v1
kind: Service
metadata:
  name: gke1
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gke1
