---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: common
  namespace: default
spec:
  template:
    spec:
      containers:
        env:
        - name: MESSAGE
          value: Hello Kubernetes! - common prod
