---
apiVersion: v1
kind: Service
metadata:
  name: common
  namespace: common
  annotations:
    fluxcd.io/automated: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: common
